// Generated by scripts/polyfit.py -- do not edit.
#pragma once

// SIN2PI: degree 7, max |error| = 7.113e-07 on [0.0, 0.25] (odd powers)
static const int SIN2PI_N = 4;
static const double SIN2PI_C[] = {6.2831675628481154, -41.337517626005578, 81.35167773428536, -71.0873581732113};

// LN1P: degree 5, max |error| = 1.018e-05 on [0.0, 1.0]
static const int LN1P_N = 6;
static const double LN1P_C[] = {9.9750325521195593e-06, 0.9992354838332751, -0.49023072342340707, 0.28527268109056397, -0.13158182508874858, 0.03044900453866459};

// EXP2N: degree 4, max |error| = 1.971e-06 on [0.0, 1.0]
static const int EXP2N_N = 5;
static const double EXP2N_C[] = {0.9999980945467194, -0.6930506671068517, 0.23943921320326672, -0.053226833517770279, 0.0068419914469185841};
