#!/usr/bin/env python3
"""Polynomial approximations for the no-LUT baselines (src/ZKmath-ext-poly.h).

Rule: the smallest degree whose (near-minimax) approximation error, after rounding the
coefficients to the working scale W = 20, is below Delta/8 = 2^-15. The fit is least squares
on 4000 Chebyshev nodes, which is within a small factor of minimax.
"""
import sys
import numpy as np

W = 20
TARGET = 2.0**-15
FUNCS = {  # name: (f, a, b, odd)
    "SIN2PI": (lambda t: np.sin(2 * np.pi * t), 0.0, 0.25, True),    # sin(2 pi t), t in [0, 1/4]
    "LN1P":   (np.log1p, 0.0, 1.0, False),                          # ln(1 + t),  t in [0, 1)
    "EXP2N":  (lambda f: 2.0**-f, 0.0, 1.0, False),                 # 2^-f,       f in [0, 1)
}


def fit(f, a, b, deg, odd):
    k = np.arange(4000)
    x = (a + b) / 2 + (b - a) / 2 * np.cos(np.pi * (k + 0.5) / 4000)
    pw = [2 * i + 1 for i in range(deg // 2 + 1)] if odd else list(range(deg + 1))
    c, *_ = np.linalg.lstsq(np.stack([x**p for p in pw], 1), f(x), rcond=None)
    cq = np.round(c * 2**W) / 2**W
    xs = np.linspace(a, b, 400001)
    err = np.max(np.abs(sum(ci * xs**p for ci, p in zip(cq, pw)) - f(xs)))
    return pw, c, err


def main():
    out = ["// Generated by scripts/polyfit.py -- do not edit.", "#pragma once", ""]
    for name, (f, a, b, odd) in FUNCS.items():
        for deg in range(3, 16, 2 if odd else 1):
            pw, c, err = fit(f, a, b, deg, odd)
            if err < TARGET:
                break
        print(f"{name}: degree {deg}, max error {err:.2e} (powers {pw})", file=sys.stderr)
        out.append(f"// {name}: degree {deg}, max |error| = {err:.3e} on [{a}, {b}]"
                   + (" (odd powers)" if odd else ""))
        out.append(f"static const int {name}_N = {len(c)};")
        out.append(f"static const double {name}_C[] = {{" + ", ".join(f"{v:.17g}" for v in c) + "};")
        out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
